### ISSUE TITLE
Missing information in ocp-ibm-cloud-roks-nfs.yaml

### ISSUE THREAD

**Issue by yefei0423** [IBM/cloud-pak-deployer#154] opened 2022-10-02 11:24 UTC
When running dynamic sample ocp-ibm-cloud-roks-nfs.yaml (https://github.com/IBM/cloud-pak-deployer/blob/main/sample-configurations/sample-dynamic/config-samples/ocp-ibm-cloud-roks-nfs.yaml), it posted the below errors.

```
TASK [lint-config : Fail if configuration errors have been found] **************
Sunday 02 October 2022  11:20:53 +0000 (0:00:00.037)       0:00:35.671 ******** 
fatal: [localhost]: FAILED! => changed=false 
  msg: |-
    Validation errors:
  
  
   
  
  
  
  
  
  
    vsi:
    infrastructure:
        keys:
        - feiye-work-provision
        primary_ipv4_address: 10.231.0.196
        public_ip: true
        subnet: feiye-work-subnet
        type: vpc
    name: feiye-work-bastion
  
    ERROR: Attribute infrastructure.image is not defined
  
  
  
    nfs_server:
    infrastructure:
        bastion_host: feiye-work-bastion
        keys:
        - feiye-work-provision
        primary_ipv4_address: 10.231.0.197
        storage_folder: /data/nfs
        storage_profile: 10iops-tier
        subnet: feiye-work-subnet
        type: vpc
        volume_size_gb: 1000
        zone: eu-de-1
    name: feiye-work-nfs
  
    ERROR: Attribute infrastructure.image is not defined
    ERROR: Attribute infrastructure.profile is not defined
```

Based on the doc https://ibm.github.io/cloud-pak-deployer/cpd-design/objects/infrastructure#ibm-cloud, they are all Mandatory.

**Comment by fketelaars** [comment] 2022-10-04 21:09
Duplicate of #120

**Closed by fketelaars** 2022-10-04 21:09 UTC
