### ISSUE TITLE
Airgap mirror problem

### ISSUE THREAD

**Issue by ugurozker** [IBM/cloud-pak-deployer#173] opened 2022-10-14 15:13 UTC
My registry ip address declared in cp4d yaml file in 192.168.70.XXX but in deployer log shows that it want to get some files in 127..0.0.1 and it gets failed after ten times retried.

FAILED - RETRYING: Mirror images from registry 127.0.0.1:12443 using /data/config/sample/case. Check status in /data/status/sample/log/cloud-pak-mirror-images.log
[5:43](https://ibm-analytics.slack.com/archives/D040FTFM8AX/p1665758637621779)

I selected only Data Privacy and Watson Knowledge Catalog for 'installed' status. Airgapped images store in our local docker registry. Those are successfully downloaded. 

That is my cp4d-451.yaml file output:

![image](https://user-images.githubusercontent.com/108928130/195880866-689f0a15-bfbe-45b1-8d6e-0fe3fd25593e.png)

![image](https://user-images.githubusercontent.com/108928130/195881345-a9e9b767-b5c7-4e6a-b640-7be235243e9b.png)

**Comment by fketelaars** [comment] 2022-10-16 06:09
Hi @ugurozker Your screen shots do not have the details of the error so I cannot make out whether the problem is with the portable registry (`127.0.0.1:12443`) or the target registry (`192.168.70.209:5000`). As the portable registry is hosted within the container, I suspect is is the target registry.

Please try the following:
```
./cp-deploy.sh env cmd
curl -v telnet://192.168.70.209:5000
```

If the curl command fails the deployer will also not be able to connect to your private registry.

**Comment by ugurozker** [comment] 2022-10-16 13:06
I checked that, deployer successfully connected to the local registry. 
![image](https://user-images.githubusercontent.com/108928130/196037040-4486d654-d5d9-45ca-8f09-35f460840f93.png)

**Comment by fketelaars** [comment] 2023-04-16 06:08
Issue with environment. Closing.

**Closed by fketelaars** 2023-04-16 06:08 UTC
