### ISSUE TITLE
Cognos Analytics fails to install on cp4d 4.7.0

### ISSUE THREAD

**Issue by David-M-IBM** [IBM/cloud-pak-deployer#495] opened 2023-08-15 20:23 UTC
Trying to install cognos analytics on cp4d 4.7.0 results in it failing during the initial installation with the logs I’ve attached that begin with “initial-failure.” The logs aren’t complete but it eventually fails with the error being “backoff limit exceeded” even though it doesn’t go through the 120 retries.

I have it setup that if the deployer job fails, then I immediately attempt to rerun the job for the cases where it fails because an operator took too long to be available in cp4d 4.7.0. And when it runs immediately afterwards it then fails with this message:

TASK [cp4d-instance-db2oltp : Get CP4D Database details] ***********************
Thursday 27 July 2023  15:07:08 +0000 (0:00:00.460)       0:12:30.169 ********* 
fatal: [localhost]: FAILED! => changed=false 
  cache_control: private
  connection: close
  content: 'Error 404 - Not Found '
  content_length: '22'
  content_type: text/plain
  date: Thu, 27 Jul 2023 15:07:09 GMT
  elapsed: 0
  etag: '"647d1329-16"'
  msg: 'Status code was 404 and not [200]: HTTP Error 404: Not Found'
  redirected: false
  server: '---'
  set_cookie: 2ac1df5a53d05af1ed3c0e46006c8757=cbf28db3154db19414328e6e55df3c08; path=/; HttpOnly; Secure; SameSite=Lax
  status: 404
  url: https://cpd-cpd.apps.ocp-666000essy-x3qg.cloud.techzone.ibm.com/icp4data/api/v1/databases
and the full logs are attached that begin with “secondary-failure.”

Looking at other issues, this may be due to the fact that I am running the job again without deleting anything that was provisioned in the previous attempt. I’ve attached my configmap, but the only components I am adding are db2 and ca.

**Desktop (please complete the following information):**
 - OS: Mac Intel 13.4.1 (c) 
 - Browser chrome
 - Version 115.0.5790.170 (Official Build) (x86_64)

**Additional context**
The deployer is being run in OpenShift 4.12 via the creation of the configmap and job.
[files.zip](https://github.com/IBM/cloud-pak-deployer/files/12352766/files.zip)

**Comment by fketelaars** [comment] 2023-08-15 20:55
This may be caused by #494 but need to check.

**Comment by fketelaars** [comment] 2023-08-17 16:26
I was able to reproduce the issue. It is related to changes in the databases API and this causes the Db2 OLTP instance to fail provisioning. The /cp4data/api/v1/databases API is no longer available in CP4D 4.7 and we need to retrieve information through another API: `/zen-data/v1/addOn/query` with body `{"add_on_type": "database"}`

I will implement the change ASAP (likely next week).

**Comment by fketelaars** [comment] 2023-08-17 16:27
As a workaround, you can provision the `ca-metastore` Db2 database manually through the UI and then re-run the deployer which will then take care of provisioning Cognos Analytics.

**Comment by fketelaars** [comment] 2023-08-17 21:02
Fixed and merged with the main branch.

**Closed by fketelaars** 2023-08-17 21:02 UTC
