### ISSUE TITLE
Container error in AnalyticEngine service setup

### ISSUE THREAD

**Issue by ugurozker** [IBM/cloud-pak-deployer#52] opened 2022-07-08 09:29 UTC
We are trying to install CP4D 4.0.9 with the Deployer tool on the existing Openshift environment. After a few hours during the installation, we see that the operators are formed properly on the OC side, but while creating the pods required for the AnalyticEngine, it falls into an error state when it takes the images related to the spark and the installation fails on bastion node's terminal. After deleting the tmp files, we tried again several times, but the problem persists.

I am sharing a picture of the error with the pods below. As far as I guess, there is a problem during the image extraction process via ansible scripts.

![image](https://user-images.githubusercontent.com/108928130/177961238-132f34a7-576e-4151-acbc-32e5a89b53e1.png)

**Cloud Environment
 - OS: OpenShift
 - Version 4.8
 - CP4D Version: 4.0.9

**Comment by fketelaars** [comment] 2022-07-11 07:01
@ugurozker My best guess is that the node running the pod is running out of space. This is not a "deployer" issue. What is the infrastructure you're running this on?

**Comment by ugurozker** [comment] 2022-07-13 13:01
Thanks for your return @fketelaars,
You can find my nodes resources and bastion node log messages at the following screenshots.
![Untitled2](https://user-images.githubusercontent.com/108928130/178739528-27622e20-d5d1-4ced-8bff-4fc9ed988d01.png)

![Untitled1](https://user-images.githubusercontent.com/108928130/178739574-3b8883b6-7c74-4866-b4c4-cc29d2f4067e.png)

**Comment by ugurozker** [comment] 2022-07-13 13:02
I need to add more details, i removed analytical engine in catalog and try to install again and this time same error caused by wml at the bastion node terminal sc.

**Comment by fketelaars** [comment] 2022-07-16 04:53
@ugurozker I will ping you, I need the logs to understand better what the issue is.

**Comment by ugurozker** [comment] 2022-07-18 08:28
[log.txt](https://github.com/IBM/cloud-pak-deployer/files/9130482/log.txt)
[cartridge.txt](https://github.com/IBM/cloud-pak-deployer/files/9130487/cartridge.txt)

Dear @fketelaars,
You can find all the logs I have obtained from bastion node attached. I'm waiting for your good news

**Comment by fketelaars** [comment] 2023-03-12 15:15
I have not been able to replay this issue and provisioning of AE consistently works. Closing.

**Closed by fketelaars** 2023-03-12 15:15 UTC
