### ISSUE TITLE
cannot install the deployer on macos due to arm64 

### ISSUE THREAD

**Issue by mohramadan911** [IBM/cloud-pak-deployer#712] opened 2024-05-13 23:06 UTC
**Describe the bug**
I am trying to install the deployer on mac m2 , however i am receiving an error 
```
./cp-deploy.sh build                                     
Building Cloud Pak Deployer container image cloud-pak-deployer:latest
COMMIT_HASH=0d38022
COMMIT_TIMESTAMP=2024-05-13T22:54:35
COMMIT_MESSAGE="Merge pull request #709 from schabrolles/cpd-cli-arch"
Error: stat /var/tmp/libpod_builder135278704/build/Dockerfile.arm64: no such file or directory
```
**To Reproduce**
- clone the repo
- on macos , i am running ./cp-deploy.sh build

**Expected behavior**
cloud-deployer support installation on non arm-64

**Desktop (please complete the following information):**
 - OS: [macos]

**Additional context**

**Comment by mohramadan911** [comment] 2024-10-06 17:18
any update on this please ?

**Comment by mohramadan911** [comment] 2024-10-06 17:18
can someone please provide a context if the deployer can run on arm64 arch ?

**Comment by fketelaars** [comment] 2024-10-06 21:16
Currently deployer cannot run on MacOS with Mx processor.

**Comment by fketelaars** [comment] 2024-10-27 21:27
Duplicate of #798 . Will try to fix.

**Closed by fketelaars** 2024-10-27 21:27 UTC
