### ISSUE TITLE
In ROKS cluster : Cloudpak deployer deamonset causing corruption of kubelet.conf file after OCP upgrade from 4.12 --> 4.13 --> 4.14 

### ISSUE THREAD

**Issue by khbash23** [IBM/cloud-pak-deployer#748] opened 2024-07-10 03:36 UTC
**Cloudpak deployer deamonset causing corruption of kubelet.conf file after OCP upgrade from 4.12 --> 4.13 --> 4.14 **

When the cloud pak deployer deamonset re-enabled after upgrade of OCP to 4.14, its causing corruption of kubelet.conf file of each worker node and resulting in **Not Ready** of worker nodes. 

**To Reproduce**
1. Upgrade the ROKS cluster from 4.12 to 4.14
2. May need to enable cloudpak deployer deamonset at least in one worker node 
3. The node will go into Not Ready state

**Comment by fketelaars** [comment] 2024-07-10 05:55
Duplicate of #747

**Closed by fketelaars** 2024-07-10 05:55 UTC
Labels: duplicate
